#!/bin/bash

set -e

DEBPATH=".travis/ide50/2015/dists/trusty/main/binary-amd64"

mv *amd64.deb $DEBPATH 2> /dev/null
cd $DEBPATH
rm Release InRelease Release.gpg Packages Packages.gz
dpkg-scanpackages . $TRAVIS_BUILD_DIR/.travis/override.trusty.main > Packages
sed -i 's/\.\///g' Packages
gzip -9c Packages > Packages.gz
apt-ftparchive release . > Release
gpg --yes --clearsign -o InRelease Release
gpg --yes -abs -o Release.gpg Release

aws s3 sync $TRAVIS_BUILD_DIR/.travis/ide50/ s3://mirror.cs50.net/ide50/
